version: '3.7'

services:
  mysql-standalone:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: football_score
    ports:
      - 3307:3306
  app:
    image: app:latest
    build:
      context: ./FootballScore/
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone
    restart: on-failure
    ports:
      - 8080:8080
