version: '3.7'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: football_score
    ports:
      - "3307:3306"
  app:
    depends_on:
      - db
    image: football:v2
    #build: "./FootballScore"
    restart: on-failure
    ports:
      - 8080:8080
