spring:
  datasource:
    url: jdbc:mysql://localhost:3306/football_site
    username: root
    password: #ASK_YOUR_COLLEAGUE#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
